version: 0.0
os: linux
files:
  - source: rankineuk/index.html
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: codedeploy_scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: codedeploy_scripts/change_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: codedeploy_scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: codedeploy_scripts/stop_server.sh
      timeout: 300
      runas: root