version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: codedeploy_scripts/install_dependencies.sh
      timeout: 300
      runas: root
    - location: codedeploy_scripts/ansible.sh
      timeout: 300
      runas: root
